CC          = <%= options[:cc] %>
LINKER      = <%= options[:linker] %>
CFLAGS      = <%= "#{options[:flags]} #{options[:cflags]}" %>
LFLAGS      = <%= "#{options[:flags]} #{options[:lflags]}" %>
LIBS        = <%= options[:libs] %>
COFLAG      = <%= options[:coflag] %>
LOFLAG      = <%= options[:loflag] %>
OUTPUT      = <%= options[:output] %>

MKDIR       = <%= options[:mkdir] %>
CP          = <%= options[:cp] %>
RM          = <%= options[:rm] %>

PROJDIR     = <%= PROJ_DIR %>

OBJECTS     = <%= OBJECTS %>

all : $(OUTPUT)

$(OUTPUT): $(OBJECTS)
	$(LINKER) $(OBJECTS) $(LIBS) $(LFLAGS) $(LOFLAG)$@

<% RULE_GROUPS.each do |dir, rule_group| %>
<%= timestamp = dir.dir_timestamp %>:
	$(MKDIR) <%= dir %>
	echo > <%= timestamp %>
<% for rule in rule_group %>
<%= rule %>
	$(CC) $(CFLAGS) <%= rule.second_token %> $(COFLAG)$@
<% end %>
<% end %>

clean:
<% RULE_GROUPS.each_key do |dir| %>
	$(RM) <%= dir %>
<% end %>
	$(RM) $(OUTPUT)
	$(RM) *.dll